// <auto-generated />
using System;
using Accoon.Pitshop.VehicleApi.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accoon.Pitshop.VehicleApi.Persistence.Migrations
{
    [DbContext(typeof(VehicleDatabaseContext))]
    partial class VehicleDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accoon.Pitshop.VehicleApi.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand")
                        .IsRequired();

                    b.Property<Guid>("Id");

                    b.Property<string>("LicenseNumber")
                        .IsRequired();

                    b.Property<string>("OwnerId");

                    b.HasKey("Type");

                    b.HasAlternateKey("Brand");

                    b.HasAlternateKey("Id");

                    b.HasAlternateKey("LicenseNumber");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
